### ISSUE TITLE
Ventura, AMD CPU, etc issues and future support of macOS in Fusion

### ISSUE THREAD

**Issue by CodeGenStudio** [DrDonk/unlocker#70]
I saw a lot of (previously) open issues regarding Ventura not working with this unlocker, and no support for AMD CPUS (mentioned in the README).

I want to say that, I did try using this unlocker with Ventura and Monterey, and it did not work (Intel i7 Gen8, Ryzen 5 Gen5). The machine hung and was stuck on a black screen in all cases.

That being said, most YouTube tutorials use this unlocker: https://github.com/paolo-projects/unlocker
I am personally using this myself, and there are no issues with Ventura launching or running - and this applies to both my AMD and Intel machines. This unlocker also worked in linking darwin.iso to the Reinstall VMware Tools option in the VM menu tab. (I had to download a copy of VMware Fusion and manually copy and paste the relevant isos - darwin.iso and darwinpre15.iso however).

I found it funny that the aforementioned unlocker was last made for Workstation 15, but it works flawlessly with Workstation 16 and 17. I suggest this repo contributors to take a look at the other repo - as this unlocker, although I couldn't get it to work - is a lot more, cleaner so to speak?

EDIT:

Quote from README:

> VMware will stop supporting new macOS versions as guests starting with Fusion 13 and the next version of ESXi.

Regarding VMware stating that, they will drop support for newer macOS versions, I think the concern there is when Apple completely transitions to ARM/M1 architecture and drops support for their Intel line of Macs.

> VMware will attempt to test and certify new macOS releases as a GOS on Fusion and add these to the VCG. However, due to the risk of unknown incompatibilities introduced in new macOS operating system releases, VMware cannot commit to supporting any future macOS operating systems releases as a GOS on Fusion.

As can be seen quoted from the VMware KB article, newer macOS versions are not going to be immediately dropped from support going forward in Fusion - only after there is no x86 build of macOS available.

Although this is controversial, Intel macs will be supported IMO for at least another 5 years - given that the extremely expensive and powerful Mac Pro was release only 2 years ago. This was expected since VMware Fusion is a hypervisor, not emulator. Anyhow, as long as Intel macs are supported, we will be able to run macOS on VMware Workstation.

**Comment by DrDonk** [comment]
Let's unpack this. I've been doing this for 15 years now in various forms on Insanely Mac and here.

1. Paolo's unlocker is a port of my unlocker v3 which was Python based. They wrote it in C++ to remove the need for Python. In the meantime I had also re-written it in Go.
2. This unlocker will unlock earlier versions (14/15) but I don't have time to test everything.
3. I have checked and Paolo's unlocker does exactly the same things as mine apart from a small marker I added to check this is V4 and not V3. Same patches for OSK keys, vmwarebase.dll for the UI macOS selection and installing darwin tools in exactly the same place. I checked that the marker does not affect functionality as I removed it and retested.
4. So I have no idea what is going on with regards to differences, although I have seen some use OCLP as well as the unlocker for AMD.
5. FYI ESXi 8 has already proven to be problematic and you must keep macOS VMs at ESXi 7 level virtual hardware or it does not boot. This was tested with several testers including one who create 100s CI macOS instances a day. 
6. Fusion will be different as Mike Roy the Fusion Product Manager has said he is trying to get better clarification including the KB), and the issue was more to do with ESXi than Fusion. (Check his Twitter posts out.)

Not sure what you want from this issue? I cannot find any differences from Paolo's unlocker that would make a difference. If that works for you then please use it. I've spent 40 years programming and I don't have any issues with someone building something better to replace what I work on, that's the nature of software development.

**Comment by DrDonk** [comment]
Closing as no updates.

**Comment by CodeGenStudio** [comment]
Apologize for the very late response.

> Paolo's unlocker is a port of my unlocker v3 which was Python based. They wrote it in C++ to remove the need for Python. In the meantime I had also re-written it in Go.

Well, I had no clue about that. Since yours is in Go and the other one in Python, I thought they were two completely different things.

> This unlocker will unlock earlier versions (14/15) but I don't have time to test everything.

No worries, that's why I asked for you to take a look into the other repo because I didn't know you both did essentially the same thing.

> FYI ESXi 8 has already proven to be problematic and you must keep macOS VMs at ESXi 7 level virtual hardware or it does not boot. This was tested with several testers including one who create 100s CI macOS instances a day.
Fusion will be different as Mike Roy the Fusion Product Manager has said he is trying to get better clarification including the KB), and the issue was more to do with ESXi than Fusion. (Check his Twitter posts out.)

Hmm I see, I will check those out.

> Not sure what you want from this issue? I cannot find any differences from Paolo's unlocker that would make a difference. If that works for you then please use it. I've spent 40 years programming and I don't have any issues with someone building something better to replace what I work on, that's the nature of software development.

Well this 'issue' wasn't necessarily an issue, I just wanted to clarify some things, and because this unlocker - like I mentioned before - looked more maintained and supported than the other one, and I just wanted to help out so you can get your unlocker working for newer versions of VMware WS. Of course it should be noted that this is before I knew that the other unlocker was a fork of your original unlocker. Tbh I am confused why yours isn't working while the other one does, but I will test the latest version you released (Dec 21, 2022) and see if it works for me. And about the Fusion things, I just wanted to clarify what you meant about the things you stated previously in your readme for this repo.

Also dang you have been programming longer than I've been alive 😂 But I didn't mean to criticize anything your doing, the support you're offering and quick responses are something a lot of developers don't do, so I sincerely appreciate that. I'm not an expert in these areas so I thought I could help you fix your issues by looking into other sources, I hope I didn't sound like I was trying to say yours was bad and the other was great and all that. Apologize if I came off rude or anything.

**Comment by DrDonk** [comment]
Hey there I suspect my reply was a little curt as had a pretty bad week, so apologies if it sounded bad. (Wife had flu, mother in hospital with flu, I fell on ice and bust my wrist, heating failed and a leak in the house!!!!)

No offence taken and I'm usually more laid back than that reply.

**Comment by CodeGenStudio** [comment]
> (Wife had flu, mother in hospital with flu, I fell on ice and bust my wrist, heating failed and a leak in the house!!!!)

That's awful! No worries, I totally understand your frustration. I hope everything is alright now.

**Comment by DrDonk** [comment]
All good now, thanks.
